version: '3.1'

services:
  joomla:
    image: joomla:3.10.9-php7.4
    restart: always
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    links:
      - joomladb:mysql
    networks:
      - webproxy
      - backend
    environment:
      JOOMLA_DB_HOST: joomladb
      JOOMLA_DB_PASSWORD: example
      JOOMLA_DB_NAME: joomla
    deploy:
      replicas: 1
      labels:
        - traefik.enable=true
        - traefik.docker.network=webproxy
        - traefik.http.routers.${APPNAME}-https.rule=Host(`${APPNAME}.${DOMAIN}`)
        - traefik.http.routers.${APPNAME}-https.entrypoints=websecure
        - traefik.http.routers.${APPNAME}-https.tls.certresolver=default
        - traefik.http.services.${APPNAME}.loadbalancer.server.port=80
      
  joomladb:
    image: mysql
    restart: always
    volumes:
      - db_data:/var/lib/mysql
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - backend
    environment:
      MYSQL_ROOT_PASSWORD: example
    deploy:
      replicas: 1
      
networks:
  webproxy:
    external: true
  backend:
  
volumes:
  db_data:
    driver: local
    driver_opts:
      device: ':/mnt/tank/${PATH}'
      o: 'addr=${NAS_SERVER},rw,noatime,rsize=8192,wsize=8192,tcp,timeo=14,nfsvers=4'
      type: nfs
  

